# Generated by Django 6.0 on 2026-01-02 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('LEARNING', 'Learning'), ('GYM', 'Gym'), ('SLEEP', 'Sleep'), ('FINANCE', 'Finance'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('ONCE', 'One-time'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom')], default='ONCE', max_length=50)),
                ('quantity', models.FloatField(blank=True, help_text='e.g., hours, reps, dollars', null=True)),
                ('unit', models.CharField(blank=True, help_text='e.g., hrs, pages', max_length=50)),
                ('progress_percent', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
